import type { Metadata } from "next";
import Nav from "@/components/Nav";
import Issues from "@/components/Issues";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <div style={{ fontSize: "2rem" }}>{children}</div>
        <Issues />
      </body>
    </html>
  );
}
